DS219/spark-seprep

- assignments/assignment-4.md
- student-introduction/urvashimohnani.md
- student-work/assignment-4/urvashimohnani.md
> add assignment 4

- git-practice/mattmorr.txt
> Add mattmorr.txt

- git-practice/rohitmandapati.md
> Add personal file

- git-practice/evan.md
- git-practice/evanleong.md
reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
> Git practice

- git-practice/hassan.md
> Initial commit

- student-work/assignment-5/hassan-dawy/containsduplicates.py
I was required to distinguish any duplicate value (appears atleast twice in a list) when given an integer array 'nums', by returning true for values that do appear atleast twice, and false for those that don't. For my soultion, I used a hashset by iterating through the list while keep track of seen numbers in a 'set()'. If a number was in the set, it would return true, otherwise it adds it and continues. I tested with a few different lists and the ones that had duplicated did in fact have True outputs.
> Added a solution for leetCode's 'Contains Duplicates' problem (#217).

- student-work/assignment-5/rohit-mandapati/palindrome.py
Implemented solution to LeetCode isPalindrome question; 
Created a new int and ran algorithm on it to set it as the input with reversed digits and compared to see if original number was a palindrome; 
Chose this solution over a String approach for better time complexity and to use as little memory as possible
> isPalindrome LeetCode Problem -- Assignment 5

- student-work/assignment-5/Hongyi-Dai/Roman-to-Int.py
-Implemented a C++ solution to convert a Roman numeral string into an integer. -Used a dictionary (unordered_map) to map Roman characters to their integer values for O(n) time complexity. -Tested the solution with a sample input "III", returning the correct output 3.
> Added a solution for LeetCode's 'Roman to Integer' problem

- student-work/assignment-5/Hrithik-Shivnauth/is_valid_problem.py
- Implemented a stack-based approach to check if a given string has valid parentheses.
- Used a dictionary to map closing brackets to their corresponding opening brackets.
- the solution runs in O(n) time complexity by processing each character once.
- Tested cases including balanced and unbalanced brackets.
> Assignment 5

- student-work/assignment-5/ahmed-almehri/merge_two_sorted_lists.py
- Implemented a Python solution that compares the smallest remaining number in each list by indexing 0
- Added the smallest number to the sorted list and removed it from the unsorted list
- Tested and passed on LeetCode
> Added a solution for LeetCode's 'Merge Two Sorted Lists' problem

- student-work/assignment-5/hibak-hussen/palindrome_number.py
Implemented a Python solution to determine if a given integer is a palindrome.
Used an efficient approach to reverse the second half of the number and compare it with the first half.
The solution handles edge cases like negative numbers, numbers that are multiples of 10 (but not zero), and single-digit numbers.
The solution runs in O(log n) time complexity and O(1) space complexity, making it highly efficient.
Tested the solution with sample inputs:
- For 121, the solution correctly returned True as it is a palindrome.
- For -121, the solution correctly returned False since negative numbers can't be palindromes.
- For 10, the solution correctly returned False, as it's not a palindrome.
> Added solution for LeetCode's 'Palindrome Number' Problem

- student-work/assignment-5/max-teo/isPalindrome.py
- Checking to see if the number is greater than 0
- Split the number up and appended into a list
- Compared the list with a reversed version to see if they are the same
> Added a solution for LeetCode's 'Palindrom Number' problem:

- add_num.py
Initializes a dummy node and a pointer current to build the result list using C++. Iterates through the lists, adding corresponding digits and the carry. Creates new nodes for the result list with the last digit of the sum and updates the carry then moves to the next nodes in l1 and l2 and returns the head of the new linked list with the sum.
> Added solution for leet codes 'add two numbers' problem

- student-work/assignment-5/Minghui-Peng/longest_common_prefix.py
- Implemented a Python solution using an iterative approach to find the longest common prefix among an array of strings.
- Tested with sample inputs: ['flower', 'flow', 'flight'] (output: 'fl').
- Time Complexity: O(S) where S is the total number of characters across all strings; Space Complexity: O(1) additional space.
> Added a solution for 'Longest Common Prefix' problem

- student-work/assignment-5/gor-matcakian/longest_common_prefix.py
- Implemented a Python solution to find the longest common prefix of an array of strings.
- Iterated through the entire array one letter at a time for O(nm) time complexity, where n is the number of strings and m is the maximum length of a string.
- Tested my solution via the LeetCode website. Got my solution accepted after the second trial.
> Added a solution for LeetCode's 'Longest Common Prefix' problem

- student-work/assignment-5/Diya-Vora/PalindromeNumber.py
- Implemented a Python solution to tell us whether a number is the same forwards and backwards
- Used conversion of string and simple comparison
- Tested the solution with a sample input [121,-121,10] ,returning target values of [True,False,False]
> Added a solution for LeetCode's 'Palindrome Number' problem

- student-work/assignment-5/cherilyn-kim/python-code
-reverse a given array of characters in-place
-use two pointers (left at the start, tight at the end) to swap characters until the pointers meet int he middle.
-print(reverseString(["h", "e", "l", "l", "o"])) output: ["o", "l", "l", "e", "h"]
> added solution for the code 

- student-work/assignment-5/jiahn-min/remove_element.py
- Implemented an in-place algorithm to remove occurrences of val.
- Used a two-pointer approach to achieve O(n) time complexity.
- Tested with nums = [3,2,2,3] and val = 3, returning new length = 2.
> Added solution for LeetCode's 'Remove Element' problem

- student-work/assignment-5/kevin-wu/two-sum.py
- Implemented a Python solution to find indices of two numbers in an array that sum to a target value.
- Used a dictionary to store previously encountered numbers and their indices for O(n) time complexity.
- Tested the solution with a sample input [2, 7, 11, 15] and target = 9, returning correct indices [0, 1].
> Added a solution for LeetCode's 'Two Sum' problem

- assignments/giagupta/reduce_a_number_to_0.py
- Implemented a Python solution to repeatedly subtract or divide the number until it reaches 0.
- Achieved O(log n) time complexity through optimized operations.
- Tested with various sample inputs to ensure correctness and efficiency.
> Added solution for 'Reduce a Number to 0' problem

- student-work/assignment-5/Azalea-Rohr/Valid-Parentheses.py
Details:
Implemented a function isValid that checks if a given string of parentheses is valid based on proper opening and closing order. Utilized a stack (leftSymbols) to store left parentheses and ensured valid matching with right parentheses. Handled edge cases, including unbalanced or incorrectly nested parentheses. Achieved O(n) time complexity by iterating through the string once. Added test cases to verify correctness with various inputs: "()" → True
"()[]{}" → True
"(]" → False
"([)]" → False
"{[]}" → True
> Added a Python solution for LeetCode's 'Valid Parentheses' problem

- student-work/assignment-5/Anissa-Patel/palindrome_number.py
- Implemented a Python solution to return True is x is a palindrome, and False otherwise.
- Used string conversion and indexing to compare characters from the beginning and end of the string.
- Tested the solution with a sample input [121, -121, 10], returning correct values [True, False, False].
> Added a solution for LeetCode's ‘Palindrome Number’ Problem

- student-work/assignment-5/sarah-rashed/palindrome_nums.py
I added a directory called 'sarah-rashed' to student-work and created a python script called palindrome_nums.py.
palindrome_nums.py is a script that takes an int and returns a bool verifying if the number is a palindrome.
there are three test cases in the script, so the output should be True, False, False.
> Sarah Rashed assignment5 PR

- imp.md
- student-work/assignment-5/evan-leong/palindrome.py
-Implemented a python solution to check validity of palindromes.
-Used a recursive if statement to check if the first and last number matched for the palindrome.
-Tested the solution with sample input '121' returning correct boolean True.
> Added a solution for LeetCode's 'Palindrome' problem

- student-work/assignment-5/MatthewMorris/TextJustification.py
Added solution to Text Justification LeetCode Problem. Implemented Python solution to iterate through all words in list. Created if statements for all 3 different cases that exist for Maxwidth (<, =, >). Used "This" "Is" "An" "Example" "of" "Text" "Justification" as my test case, with max width 10.
> Assignment5 - TextJustification

- student-work/assignment-5/riwaz-shrestha/remove_element.py
- Implemented a Python solution to replace values of val in a list of nums.
- Used a for loop to itterrate through a list of nums and replace the first k elements (with k being the number of values in the list that are not equal to val) with values that are not equal to val.
- Tested the solution with a sample input [3,2,2,3] and val = 3, returning [2,2,2,3].
> Added a solution for LeetCode's 'Remove Element' problem

- student-work/assignment-5/john-kinney/fizz_buzz.py
- Created a function `fizz_buzz(n)` that generates a list of FizzBuzz values up to `n`.
- Used a while loop to iterate through numbers, appending "Fizz" for multiples of 3, "Buzz" for multiples of 5, and "FizzBuzz" for multiples of both.
- Included a test case with `fizz_buzz(3)`, correctly outputting `["1", "2", "Fizz"]`.
> Added a solution for LeetCode's 'Fizz Buzz' problem

- student-work/assignment-4/evanleong.md
For my assignment 4! Shoutout to everyone who helped me out.
> Evan Leong: Assignment 4

- student-work/assignment-4/HrithikShivnauth.md
This is a pull request for assignment 4.
> HrithikShivnauth: Assignment 4

- student-work/assignment-4/mattmorr.md
> Assignment 4 branch

- student-work/assignment-4/minseokcho.md
Requesting Pull from my computer to upstream.
> minseokcho.md: Assignment 4

- student-work/assignment-4/sarahrashed.md
> Sarah Rashed Assignment 4

- student-work/assignment-4/soumyamehta.md
> Soumya Mehta: Assignment 4

- student-work/assignment-4/perlards.md
pull request to the main upstream repository (DS219/spark-seprep) containing the changes to student-work/perlards.md
> [Perla Ruiz]: Assignment 4

- student-work/assignment-4/Sachiel-Chuckrow.md
- student-work/assignment-5/Sachiel-Chuckrow/longest-substring.py
Added Function For Assignment 5 - Longest substring.
> Assignment5

- student-work/assignment-4/liamdurcan.md
- student-work/assignment-5/Liam-Durcan/LiamDurcan_DS219_SortedSquaresLeetcode.py
This includes my work from last week as well, which I'm now realizing I didn't complete the final pull request for like I thought I did. Sorry for the mishap/confusion. Let me know if anything needs changed/corrected, I'm still getting the hang of navigating git and github. Thanks!
-LD
> Assignments 4 & 5

- student-work/assignment-4/sanskrutiodhe.md
I resolved authentication errors by switching my repository’s remote from HTTPS to SSH and confirming GitHub’s host key. After that, I pushed my changes to GitHub without needing a username/password, set up an upstream remote to track the main repository, created a new branch (assignment-4-branch), added my sanskrutiodhe.md file, and pushed those changes for the assignment’s pull request.
> sanskruti odhe: hw 4

- student-work/assignment-5/liam-ben-zvi/palindrome
This is a python script that checks if a number reversed is equal to the inputted number. For example 121 returns true and 122 returns false because the reverse of 121 is 121 and the reverse of 122 is 221.
> Added my favorite problem, palindrome check solution

- student-work/assignment-7/john-kinney/ContainerFile
- student-work/assignment-7/john-kinney/quote.sh
- Created a ContainerFile to define a container that fetches a random quote. 
- Added quote.sh script to retrieve a random quote and author using curl and jq.
> Added a container solution to fetch and display random quotes

- student-work/assignment-7/MINSEOK-CHO/Containtefile
- student-work/assignment-7/MINSEOK-CHO/Merge_Alt.py
> assignment 7 work

- student-work/assignment-7/LIAM-DURCAN/Assignment7.py
- student-work/assignment-7/LIAM-DURCAN/Containerfile
When built and ran, this container for assignment 7 will count off and print 3 Hello World statements resulting from some Python code I wrote. The two files are the file of python code along with the Containerfile
> Liam Durcan Assignment 7 

- palindrome.py
- student-work/assignment-7/Krisha-Shetty/Containerfile
palindrome.py and Container file added
> Added palindrome.py and Containerfile after completing steps in podman.

- student-work/assignment-7/riwaz-shrestha/ContainerFile
- student-work/assignment-7/riwaz-shrestha/script.py
This is my pull request for assignment 7, Creating a Container Image.
> assignment7

- student-work/assignment-7/hibak-hussen/Dockerfile
- student-work/assignment-7/hibak-hussen/rectangle.py
- Dockerfile: Added a Dockerfile to containerize the Python app.
- rectangle.py: Implemented a Python script to calculate and print the area of a rectangle.
> Dockerfile and Python script for rectangle area calculation

- student-work/assignment-7/Christian-Hilario/Containerfile
- student-work/assignment-7/Christian-Hilario/script.py
Implemented a python script that finds the length of the of the longest substring without repeating characters by using a function (longest_substring(s)) which creates a hashmap and enumerates through the string. The function does this with a for loop iterating through the map with an if statement comparing the current character and the character to the right of the current one, while stopping at the end of the string and checking if the character is the same as the one before it and counting it if the letter is not the same as the previous one. The example output is 3 for the string "abcabcbb".
> Assignment 7 Christian Hilario

- student-work/assignment-7/hassan-dawy/Containerfile
- student-work/assignment-7/hassan-dawy/containsduplicates.py
This PR adds my solution for Assignment 7, which involves containerizing the containsduplicates.py script using Podman. The Containerfile sets up a Python environment, copies the script, and executes it inside a container.
Changes Included:
- Added containsduplicates.py to student-work/assignment-7/hassan-dawy/
- Created a Containerfile to containerize the script
- Built and tested the image using Podman
- Pushed the image to Docker Hub: docker.io/hassan-dawy/containsduplicates-container
> Assignment 7 homework -- Containerized containsduplicates.py script -- Hassan Dawy

- student-work/assignment-7/Hrithik-Shivnauth/Containerfile
- student-work/assignment-7/Hrithik-Shivnauth/isvalid.py
> Assignment 7 files

- student-work/assignment-7/Soumya-Mehta/Containerfile
- student-work/assignment-7/Soumya-Mehta/palindrome.py
Palindrome.py has a code to check whether or not a giver number is palindrome. Containerfile helps to build a containerimage. I found and printed container images, for numbers 10 to 200.
> Add palindrome.py and containerfile

- student-work/assignment-5/AymenTiguite/RomantoInteger.py
- Implemented a Python solution that converts a Roman numeral string to an integer.
- Achieves O(n) time complexity by traversing the input string once.
- Utilizes O(1) space by using only a few variables and no extra data structures.
- Tested the solution with various examples (e.g., 'III', 'IV', 'IX', 'LVIII', 'MCMXCIV') to ensure correctness.
> Added solution for LeetCode's 'Roman to Integer' problem

- student-work/assignment-7/sanskruti-odhe/Containerfile
- student-work/assignment-7/sanskruti-odhe/my_script.py
- my_script.py: prints greeting & sample LeetCode output
- Containerfile: packages it on python:3.9-slim, CMD → ./my_script.py
> Add Assignment 7 script + Containerfile

- student-work/assignment-8/SanskrutiOdhe/Assignment8-SanskrutiOdhe.ipynb
- student-work/assignment-8/SanskrutiOdhe/Containerfile
- student-work/assignment-8/SanskrutiOdhe/requirements.txt
- Comprehensive EDA: histograms, boxplots, countplots, heatmap
- Three hypotheses & rigorous tests (t-test, chi-sq, KS)
- Extra credit: logistic regression AUC, missing-value analysis, pairplot
> Add Assignment 8 EDA & Hypothesis Testing notebook by Sanskruti Odhe
