DS219/spark-seprep

student-introduction/rida.md
Added markdown file for assignment 3
=> Rida: Assignment 3

student-introduction/laerk.md
=> assignment 3

student-introduction/ajanihickling.md
Commit including Ajani Hickling's submission of Assignment 3.
=> Ajani Hickling : Assignment 3

student-introduction/rahil.md
=> Rahil Shah: Assignment 3

student-introduction/gersian.md
=> [Gersian Collaku]: Assignment 3

student-introduction/wei.md
contribute to student introduction file
Wei
=> wei: assignment 3

student-introduction/akshat.md
=> [akshat sharma]: Assignment 3

student-introduction/rachelyoung.md
=> [rachelyoung]: Assignment 3

student-introduction/jadenhsiao.md
This is my pull request to add my assignment 3 for DS219.
=> Jaden Hsiao: Assignment 3

student-introduction/andyyang.md
Added andyyang.md to student-introductions
=> Andy Yang Introduction

student-introduction/anngo.md
=> An Ngo: Assignment 3

student-introduction/kristenbestavros.md
=> Kristen Bestavros: Assignment 3

student-introduction/saralin.md
My favorite programming language
=> Sara Lin: Assignment 3

assignments/assignment4/assignment4.md
adding markdown files created by myself and Laerk
=> Assignment4

assignments/assignment4/assignment4.md, student-introduction/gersian.md
Added Team4/Andy.md and Team4/Truc.md
=> Team4 Assignment 4 final PR

assignments/containerfiles/GEORGE-TRAMMELL/Containerfile, assignments/containerfiles/GEORGE-TRAMMELL/assignment6.py
=> George Trammell: Assignment 6

assignments/containerfiles/MATT-FRYSINGER/122hw6.py, assignments/containerfiles/MATT-FRYSINGER/Dockerfile-MF
=> assignment6

assignments/containerfiles/AJANI-HICKLING/Containerfile, assignments/containerfiles/AJANI-HICKLING/echo_test.sh
Assignment 6 submission. Contains Containerfile and executable, echo_test.sh
=> Adding Container file and executable for assignment 6

assignments/containerfiles/wei-mai/Containerfile, assignments/containerfiles/wei-mai/script.py
=> added wei's containerfile and script

assignments/containerfiles/SEAN-LIN/Containerfile, assignments/containerfiles/SEAN-LIN/colors.sh
Assignment 6 containerfile and the bash script
=> Assignment 6: add Containerfile and bash script file

assignments/containerfiles/FaresSakaan/ContainerFile, assignments/containerfiles/FaresSakaan/joke.sh
=> Very late assignment 6 with help from Sally

assignments/containerfiles/yujia-zhai/Containerfile, assignments/containerfiles/yujia-zhai/integer.sh
=> assignment6: containerfiles

assignments/containerfiles/JADEN-HSIAO/script.py
In this PR adding my python file, missed it in previous PR. @umohnani8
=> commiting python file

assignments/containerfiles/Oluwaseun-Ademiloye/Containerfile, assignments/containerfiles/Oluwaseun-Ademiloye/avg_calculator.py
I worked with Professor Sally on this assignment
=> assignment 6 containerfile

assignments/assignment8/yujiazhai/assignment8.md
=> Assignment8
